name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Build Docker image
        run: docker build . --file Dockerfile --platform linux/amd64 -t makenzik95/firstreact-app:${GITHUB_SHA::6}
        
      - name: Push to Docker Hub
        run: docker push makenzik95/firstreact-app:${GITHUB_SHA::6}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ec2-54-90-142-56.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }} 
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 80:8080 makenzik95/firstreact-app:${GITHUB_SHA::6}
            docker ps
