name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Build Docker image
        run: docker build . --file Dockerfile --platform linux/amd64 -t makenzik95/firstreact-app:${{ github.sha }}
        
      - name: Push to Docker Hub
        run: docker push makenzik95/firstreact-app:${{ github.sha }}

      - name: multiple command
        uses: appleboy/ssh-action@v1.0.0
        env:
          IMAGETAG: ${{ github.sha }}
        with:
          host: ec2-54-90-142-56.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }} 
          envs: IMAGETAG
          script: |
             docker run -d -p 80:80 makenzik95/firstreact-app:${{ github.sha }}
